[package]
name = "asgart"
version = "1.4.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
superslice   = "0.1"
bio          = "*"
colored      = "1.*"
console      = "0.6"
env_logger   = "0.5"
error-chain  = "0.12"
indicatif    = "0.9"
isatty       = "0.1"
log          = "0.4"
num_cpus     = "1.*"
palette      = "0.4"
rand         = "0.5"
rayon        = "1.*"
regex        = "1.*"
serde        = "1.*"
serde_derive = "1.*"
serde_json   = "1.*"
separator    = { git = "https://github.com/delehef/rust-separator.git" }
threadpool   = "1.*"
uuid         = "0.6"
human-panic  = "1.0"


[dependencies.clap]
version = "2.*"
features = [ "yaml", "suggestions", "color" ]

[profile.release]
debug = true

[build-dependencies]
cmake = "0.1"
