[package]
name = "asgart"
version = "1.2.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
bio             = "*"
num_cpus        = "*"
uuid            = "*"
threadpool      = "1.*"
rand            = "0.3"
rustc-serialize = "0.3"
palette         = "0.2"
log             = "0.3"
env_logger      = "0.4"
colored         = "1.*"
isatty          = "0.1"
indicatif       = "0.7"
console         = "0.5"
rayon           = "0.8"
error-chain     = "0.11"
regex           = "0.2"
separator       = { git = "https://github.com/delehef/rust-separator.git" }

[dependencies.clap]
version = "2.*"
features = [ "yaml", "suggestions", "color" ]

[profile.release]
debug = false

[build-dependencies]
cmake = "0.1"
