[package]
name = "asgart"
version = "1.5.0"
authors = ["Franklin Delehelle <franklin.delehelle@irit.fr>"]
license = "GPLv3"

[dependencies]
atty         = "0.2"
bio          = "*"
colored      = "1.*"
console      = "0.7"
env_logger   = "0.6"
error-chain  = "0.12"
human-panic  = "1.0"
indicatif    = "0.11"
log          = "0.4"
num_cpus     = "1.*"
palette      = "0.4"
rand         = "0.6"
rayon        = "1.*"
regex        = "1.*"
separator    = { git = "https://github.com/delehef/rust-separator.git" }
serde        = "1.*"
serde_derive = "1.*"
serde_json   = "1.*"
superslice   = "1.0"
threadpool   = "1.*"
uuid         = "0.7"


[dependencies.clap]
version = "2.*"
features = [ "yaml", "suggestions", "color"]

[profile.release]
debug = true

[build-dependencies]
cmake = "0.1"
